/* Ejer : Borrar tabla */
DROP TABLE ALUMNOS;

/* Ejer : Crear tabla */
CREATE TABLE ALUMNOS(
	DNI 	VARCHAR2(10),	
	NOMBRE 	VARCHAR2(30) 	 NOT NULL, 
	EDAD 	NUMBER(2),
	CURSO 	NUMBER(1),
	CONSTRAINT 	ALU_DNI_PK 	PRIMARY KEY(DNI),
	CONSTRAINT	ALU_EDA_CK 	CHECK (EDAD BETWEEN 5 AND 20), 
	CONSTRAINT 	ALU_NOM_CK  CHECK (NOMBRE=UPPER(NOMBRE)), 
	CONSTRAINT 	ALU_CUR_CK  CHECK (CURSO IN(1,2,3)) );