/*PARTE 4 enunuciado*/
/* EJERCICIO 5 */
DROP TABLE ALUMNOS;
DROP TABLE PROVINCIAS CASCADE CONSTRAINTS;

/* EJERCICIO 1 */
CREATE TABLE ALUMNOS(
DNI varchar2(10),
NOMBRE varchar2(30) NOT NULL,
EDAD number(2),
CURSO number(1),	
CONSTRAINT ALU_DNI_PK PRIMARY KEY (DNI),
CONSTRAINT ALU_EDA_CK CHECK (EDAD BETWEEN 5 AND 20),
CONSTRAINT ALU_NOM_CK CHECK (NOMBRE UPPER(NOMBRE)),
CONSTRAINT ALU_CUR_CK CHECK (CURSO IN(1,2,3)) 
);

/*CONSTRAINT ALU_DNI_PK CHECK (EDAD >= 5 | <= 20)*/
CREATE TABLE ALUMNOS(
DNI varchar2(10) CONSTRAINT ALU_DNI_PK PRIMARY KEY,
NOMBRE varchar2(30) NOT NULL,
EDAD number(2),
CURSO number(1),
CONSTRAINT ALU_EDA_CK CHECK (EDAD BETWEEN 5 AND 20),
CONSTRAINT ALU_NOM_CK CHECK (NOMBRE=UPPER(NOMBRE)),
CONSTRAINT ALU_CUR_CK CHECK (CURSO IN(1,2,3))
);

/* EJERCICIO 2: */
DESCRIBE ALUMNOS:
ALTER TABLE ALUMNOS
	ADD(SEXO varchar2(1) NOT NULL, IMPORTE NUMBER(10, 2));
ALTER TABLE ALUMNOS
	MODIFY (IMPORTE DEFAULT 0);
ALTER TABLE ALUMNOS
	ADD CONSTRAINT ALU_SEXO_CK CHECK (SEXO IN ('M', 'F'));
ALTER TABLE ALUMNOS
	ADD (SEXO CHAR NOT NULL
			CONSTRAINT ALU_SEXO_CK CHECK (SEXO IN ('M', 'F')))

/*Inicio ejercicio 3: */
SELECT CONSTRAINT_NAME, TABLE_NAME, CONSTRAINT_TYPE 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'ALUMNOS'

INSERT INTO ALUMNOS VALUES('1111', 'Petpe', 4, 1);
INSERT INTO ALUMNOS VALUES('1111', 'PEPE', 4, 1);
INSERT INTO ALUMNOS VALUES('1112', 'PEPE', 10, 2);
INSERT INTO ALUMNOS VALUES('1113', 'MARIA', 32, 2);																																												
INSERT INTO ALUMNOS VALUES('2222', 'MARIA', 12, 5);																																																																																																																																								
INSERT INTO ALUMNOS VALUES('2224', 'MARIA', 22, 3);

/*1º*/
DESC USER_TABLES(paso previo para conocer NOMBRE de COLUMNAS);
SELECT TABLE NAMES FROM USER_TABLES WHERE lower(TABLE_NAME)="alumnos";

/*2º*/
DESC ALUMNOS;

/*Paso previo al 3º*/
DESC USER_CONSTRAINTS /*-------> Muestra los NOMBRES de la COLUMNAS de la */
/*3º*/

/*******************************************/

SELECT TABLE_NAME, CONTRAINT_NAME, CONSTRAINT_TYPE 
FROM USER_CONTRAINTS
WHERE TABLE_NAME IS ('PROVINCIAS', 'PERSONAS');

/*WHERE TABLE_NAME ='PROVINCIAS' OR TABLE_NAME='PERSONAS'*/

SELECT TABLE_NAME, CONTRAINT_NAME, CONSTRAINT_TYPE 
FROM USER_CONTRAINTS
WHERE TABLE_NAME IS ('PROVINCIAS', 'PERSONAS');

/* EJERCICIO 4: */
ALTER TABLE ALUMNOS ADD (FECHA_NAC DATE, FECHA_ALTA DATE)
ALTER TABLE ALUMNOS ADD CONSTRAINT
CONSTRAINT ALU_FEC_CK CHECK (FECHA_NAC < FECHA_ALTA);

ALTER TABLE ALUMNOS ADD
(FECHA_NAC DATE,
FECHA_ALTA DATE,
CONSTRAINT ALU_FEC_CK CHECK (FECHA_NAC < FECHA_ALTA)
);

/* EJERCICIO 6: */
ALTER TABLE ALUMNOS RENAME COLUMN IMPORTE TO TASAS;

/* EJERCICIO 7: */
ALTER TABLE ALUMNOS DROP (FECHA_NAC);