REM ******** TABLA DEPART: *********** 

DROP TABLE DEPART CASCADE CONSTRAINTS; 

CREATE TABLE DEPART (
 	DEPT_NO  NUMBER(2),
	DNOMBRE  VARCHAR2(14), 
 	LOC      VARCHAR2(14),
	CONSTRAINT DEP_PK PRIMARY KEY (DEPT_NO)
	);

INSERT INTO DEPART VALUES (10,'CONTABILIDAD','SEVILLA');
INSERT INTO DEPART VALUES (20,'INVESTIGACION','MADRID');
INSERT INTO DEPART VALUES (30,'VENTAS','BARCELONA');
INSERT INTO DEPART VALUES (40,'PRODUCCION','BILBAO');

COMMIT;

REM /*  ******** TABLA EMPLE: ************* */

DROP TABLE EMPLE CASCADE CONSTRAINTS; 

CREATE TABLE EMPLE (
 	EMP_NO    NUMBER(4),
 	APELLIDO  VARCHAR2(10),
 	OFICIO    VARCHAR2(15),
 	ID_JEFE  NUMBER(4) ,
 	FECHA_ALTA DATE,
 	SALARIO   NUMBER(9) NOT NULL,
 	COMISION_PCT  NUMBER(3),
 	DEPT_NO   NUMBER(2) NOT NULL,
	CONSTRAINT EMPLE_PK PRIMARY KEY (EMP_NO),
	CONSTRAINT EMPLE_DIR_FK FOREIGN KEY (ID_JEFE)
				REFERENCES EMPLE(EMP_NO)  ON DELETE SET NULL,
	CONSTRAINT EMPLE_DEP_FK FOREIGN KEY (DEPT_NO)
				REFERENCES DEPART(DEPT_NO) ON DELETE CASCADE);

INSERT INTO EMPLE VALUES (7839,'REY','PRESIDENTE',NULL,
                            TO_DATE('17/11/1981','DD/MM/YYYY'),6500,NULL,10);
INSERT INTO EMPLE VALUES (7566,'JIMENEZ','GERENTE',7839,
                            TO_DATE('12/04/1981','DD/MM/YYYY'),3867,NULL,20);
INSERT INTO EMPLE VALUES (7698,'NEGRO','GERENTE',7839,
                            TO_DATE('11/05/1981','DD/MM/YYYY'),3705,NULL,30);
INSERT INTO EMPLE VALUES (7782,'CEREZO','GERENTE',7839,
                            TO_DATE('19/06/1981','DD/MM/YYYY'),3185,NULL,10);
INSERT INTO EMPLE VALUES (7788,'GIL','ANALISTA',7566,
                            TO_DATE('19/11/1981','DD/MM/YYYY'),3900,NULL,20);
INSERT INTO EMPLE VALUES (7902,'FERNANDEZ','ANALISTA',7566,
                            TO_DATE('13/12/1981','DD/MM/YYYY'),3900,NULL,20);
INSERT INTO EMPLE VALUES (7499,'ARROYO','COMERCIAL',7698,
                            TO_DATE('20/02/1980','DD/MM/YYYY'),2080,10,30);
INSERT INTO EMPLE VALUES (7521,'SALA','COMERCIAL',7698,
                            TO_DATE('22/02/1981','DD/MM/YYYY'),1625,5,30);
INSERT INTO EMPLE VALUES (7654,'MARTIN','COMERCIAL',7698,
                            TO_DATE('29/09/1981','DD/MM/YYYY'),1625,5,30);
INSERT INTO EMPLE VALUES (7844,'TOVAR','COMERCIAL',7698,
                            TO_DATE('18/09/1981','DD/MM/YYYY'),1950,8,30);
INSERT INTO EMPLE VALUES (7900,'JIMENO','PROGRAMADOR',7566,
                            TO_DATE('13/12/1981','DD/MM/YYYY'),1235,NULL,30);
INSERT INTO EMPLE VALUES (7369,'SANCHEZ','PROGRAMADOR',7566,
                            TO_DATE('17/12/1980','DD/MM/YYYY'),1040,NULL,20);
INSERT INTO EMPLE VALUES (7876,'ALONSO','PROGRAMADOR',7788,
                            TO_DATE('23/09/1981','DD/MM/YYYY'),1430,NULL,20);
INSERT INTO EMPLE VALUES (7934,'SANCHEZ','AUXILIAR',7782,
                            TO_DATE('23/01/1982','DD/MM/YYYY'),1690,NULL,10);

COMMIT;

/*Ejercicio 3-1*/

INSERT INTO DEPART (DEPT_NO, DNOMBRE, LOC) VALUES (11, 'CALIDAD', 'Santader');
INSERT INTO EMPLE (EMP_NO, APELLIDO, OFICIO, DEPT_NO,ID_JEFE, SALARIO,
            FECHA_ALTA) VALUES (7230, 'AGUIRRE', 'EMPLEADO', 11, 0, SYSDATE);
            
/*Ejercicio 3-2*/

SELECT EMP_NO, SALARIO
FROM EMPLE;
/*

    EMP_NO    SALARIO
---------- ----------
      7839       6500
      7566       3867
      7698       3705
      7782       3185
      7788       3900
      7902       3900
      7499       2080
      7521       1625
      7654       1625
      7844       1950
      7900       1235
*/
UPDATE EMPLE
SET SALARIO = SALARIO * 0.9;

SELECT EMP_NO, SALARIO
FROM EMPLE;
/*

    EMP_NO    SALARIO
---------- ----------
      7369       1040
      7876       1430
      7934       1690

*/

/*Ejercicio 3-3*/

SELECT DEPT_NO, EMP_NO
FROM EMPLE
WHERE DEPT_NO = 10;
/*

   DEPT_NO     EMP_NO
---------- ----------
        10       7839
        10       7782
        10       7934
*/
UPDATE EMPLE
SET DEPT_NO = 40
WHERE DEPT_NO = 10;

SELECT DEPT_NO, EMP_NO
FROM EMPLE
WHERE DEPT_NO IN (10, 40);
/*
   DEPT_NO     EMP_NO
---------- ----------
        40       7839
        40       7782
        40       7934
*/

/*Ejercicio 3-4*/

SELECT EMP_NO, ID_JEFE
FROM EMPLE
WHERE ID_JEFE = 7566;

SELECT EMP_NO, ID_JEFE
FROM EMPLE
WHERE LOWER(APELLIDO) LIKE '%tovar%';

UPDATE EMPLE
SET ID_JEFE = (SELECT ID_JEFE
                FROM EMPLE
                WHERE LOWER(APELLIDO) LIKE '%tovar%')
WHERE ID_JEFE = 7566;

SELECT EMP_NO, ID_JEFE
FROM EMPLE
WHERE ID_JEFE IN (7566,(SELECT ID_JEFE
                  FROM EMPLE
                  WHERE LOWER(APELLIDO) LIKE '%tovar%'));
                  
/*Ejercicio 3-5*/

SELECT SALARIO
FROM EMPLE
WHERE LOWER(APELLIDO) LIKE '%muñoz%';

SELECT SALARIO, EMP_NO
FROM EMPLE
WHERE LOWER(OFICIO) = 'empleado';

UPDATE EMPLE
SET SALARIO = (SELECT SALARIO
                FROM EMPLE
                WHERE LOWER(APELLIDO) = 'muñoz')
WHERE LOWER(OFICIO) = 'empleado';
/*Da error, porque muñoz no existe. Ademas hay una restricción not null*/

/*Solución corregida con funciones:*/
UPDATE EMPLE
SET SALARIO = NVL((SELECT SALARIO
                FROM EMPLE
                WHERE LOWER(APELLIDO) = 'muñoz'), 0)
/*COn NVL((select....), 0) en caso de tener un valor null se sustitulle por 0,
la restricción es de tipo not null*/
WHERE LOWER(OFICIO) = 'empleado';   

SELECT SALARIO, EMP_NO
FROM EMPLE
WHERE LOWER(OFICIO) = 'empleado';

/*Ejercicio 3-6*/

SELECT EMP_NO, DEPT_NO, COMISION_PCT
FROM EMPLE
WHERE DEPT_NO = (SELECT DEPT_NO 
                FROM DEPART
                WHERE UPPER(LOC) = 'SANTANDER');
                
UPDATE EMPLE
SET COMISION_PCT = 300
WHERE DEPT_NO = (SELECT DEPT_NO
                FROM DEPART
                WHERE UPPER(LOC) = 'SANTANDER');
                
SELECT EMP_NO, DEPT_NO, COMISION_PCT
FROM EMPLE
WHERE DEPT_NO = (SELECT DEPT_NO 
                FROM DEPART
                WHERE UPPER(LOC) = 'SANTANDER');

/*Ejercicio 3-7*/

SELECT EMP_NO, DEPT_NO
FROM EMPLE
WHERE DEPT_NO = 30;

DELETE
FROM EMPLE
WHERE DEPT_NO = 30;

SELECT EMP_NO, DEPT_NO
FROM EMPLE
WHERE DEPT_NO = 30;

/*Select_funciones_de_fila*/

/*Ejercicio_1*/

SELECT APELLIDO AS "Empleado", NVL(TO_CHAR(ID_JEFE), 'NO TIENE JEFE') AS "JEFE"
FROM EMPLE
ORDER BY ID_JEFE DESC;

/*Se utiliza el nvl en el select en este caso no requiere de un where*/
/*Ejercicio_2*/           

SELECT EMP_NO AS "Empleado", SALARIO AS "Salario",
        TRUNC(SALARIO/1000) AS "PORCENTAJE DE MOVILIZACION" 
FROM EMPLE;

/*Ejercicio_3*/

SELECT APELLIDO AS "apellido", OFICIO AS "trabajador",
        INITCAP(SUBSTR(APELLIDO, 1, 3)) ||LENGTH(APELLIDO) ||
        OFICIO AS "nombre_ususario", TO_CHAR(FECHA_ALTA, 'MMYYYY') ||
        UPPER(SUBSTR(APELLIDO, 2)) AS "CLAVE USUARIO"
FROM EMPLE
ORDER BY APELLIDO;

/*Ejercicio_4*/

SELECT APELLIDO AS "NOMBRE EMPLEADO",
        TO_CHAR(SALARIO, '999,999.999') AS "Salario",
        TO_CHAR((SALARIO * SUBSTR(SALARIO, 1, 1)/100),'9,999.999') AS Reajuste
FROM EMPLE;

/*Ejercicio_5*/

SELECT EMP_NO AS "ID EMPLEADO", SALARIO AS "SALARIO SIN COMISION",
        NVL(TO_CHAR(COMISION_PCT), 'SIN COMISION') AS "PORC. COMISION",
        NVL2(COMISION_PCT, SALARIO*COMISION_PCT/100,0) AS "VALOR COMISION",
        NVL2(COMISION_PCT, SALARIO*(SALARIO*COMISION_PCT/100),SALARIO) 
        AS "SALARIO TOTAL"
FROM EMPLE;

/*Ejercicio_6*/

SELECT EMP_NO, FECHA_ALTA,
    TRUNC(MONTHS_BETWEEN(SYSDATE,FECHA_ALTA),0) AS "MESES",
    ADD_MONTHS(FECHA_ALTA,6) AS "REVISION", NEXT_DAY(FECHA_ALTA, 'VIERNES'),
    LAST_DAY(FECHA_ALTA)
FROM EMPLE
WHERE MONTHS_BETWEEN(SYSDATE,FECHA_ALTA)*460;