DROP TABLE PERSONAS;
DROP TABLE PROVINCIAS CASCADE CONSTRAINTS;

/*Creo la tabla PROVINCIAS con la restricción PK */
CREATE TABLE PROVINCIAS(
COD_PROV number(2),
NOM_PROV varchar2(15),
CONSTRAINT prov_cod_pk PRIMARY KEY (COD_PROV)
);

/*Creo la tabla PERSONAS con las restricciones PK y FK */
CREATE TABLE PERSONAS(
DNI number(8) PRIMARY KEY,
NOMBRE varchar2(15),
DIRECCION varchar2(15),
POBLACION varchar2(20),
COD_PROV number(2) REFERENCES PROVINCIAS
);

CREATE TABLE PERSONAS(
DNI number(8) CONSTRAINT PER_DNI_PK PRIMARY KEY,
NOMBRE varchar2(15),
DIRECCION varchar2(15),
POBLACION varchar2(20),
COD_PROV number(2) CONSTRAINT PERS_COD_FK REFERENCES PROVINCIAS
);

/* Cambiar de nombre a la tabla */
RENAME PERSONAS TO CIUDADANOS;


